
APP_VERSION = "0.0.4"
CONTAINER_URL = "ghcr.io/shopsd/homeassistant-grandstream-gwn"
PYTHON_VERSION = "3.14.2"
PYTHON_REQUIRES = ">=3.14.2"
HOMEASSISTANT_MIN_VERSION = "2026.6.2"
INTEGRATION_NAME = "Grandstream GWN Manager Bridge"
LIBRARY_AIOHTTP_VERSION=">=3.13.2"
LOGGERS = "gwn_mqtt"
REPOSITORY_URL = "https://github.com/shopsD/grandstream-gwn-homeassistant-mqtt"
UPDATE_URL = "https://api.github.com/repos/shopsD/grandstream-gwn-homeassistant-mqtt/releases"
