
APP_VERSION = "0.0.3"
PYTHON_VERSION = "3.14.2"
PYTHON_REQUIRES = ">=3.14.2"
HOMEASSISTANT_MIN_VERSION = "2026.5.2"
REPOSITORY_URL = "https://github.com/shopsD/homeassistant-grandstream-gwn"
CONTAINER_URL = "ghcr.io/shopsd/homeassistant-grandstream-gwn"
UPDATE_URL = "https://api.github.com/repos/shopsD/homeassistant-grandstream-gwn/releases"
LOGGERS = "gwn_mqtt"
INTEGRATION_NAME = "Grandstream GWN Manager Bridge"
