DOMAIN = "grandstream_gwn"
PLATFORMS = ["sensor", "button", "switch", "text", "select"]

CLIENT_CONFIG_KEY = "gwn_client_config"
CLIENT_KEY = "client"
CONFIG_KEY = "config"
FLOW_ID_KEY = "flow_id"

APP_ID_CONFIG_KEY = "app_id"
SECRET_KEY_CONFIG_KEY = "secret_key"
RESTRICTED_API_CONFIG_KEY = "restricted_api"
USERNAME_CONFIG_KEY = "username"
PASSWORD_CONFIG_KEY = "password"
BASE_URL_CONFIG_KEY = "base_url"
PAGE_SIZE_CONFIG_KEY = "page_size"
MAX_PAGES_CONFIG_KEY = "max_pages"
REFRESH_PERIOD_S_CONFIG_KEY = "refresh_period_s"
EXCLUDE_PASSPHRASE_CONFIG_KEY = "exclude_passphrase"
EXCLUDE_SSID_CONFIG_KEY = "exclude_ssid"
EXCLUDE_DEVICE_CONFIG_KEY = "exclude_device"
EXCLUDE_NETWORK_CONFIG_KEY = "exclude_network"
IGNORE_FAILED_FETCH_BEFORE_UPDATE_CONFIG_KEY = "ignore_failed_fetch_before_update"
SSID_NAME_TO_DEVICE_BINDING_CONFIG_KEY = "ssid_name_to_device_binding"
NO_PUBLISH_CONFIG_KEY = "no_publish"
